version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        depends_on:
            - db
        expose:
            - 9000

    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        depends_on:
            - app

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: XrChmP6Q9EwRvHheHE1o2MWDPZXUhOAX
            POSTGRES_DB: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
